apiVersion: v1
kind: LimitRange
metadata:
  name: my-limit-range
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 200Mi
    default:
      cpu: 200m
      memory: 500Mi
    min:
      cpu: 50m
      memory: 100Mi
    max:
      cpu: 500m
      memory: 1Gi